### PR TITLE
Update to documentation for June 2024 the 5th release 

### PR DESCRIPTION
**Pull request by Brunoga-MS**
# Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. *Updated deployment method pages with the latest changes on the param file*
2. *Added the documentation on how to update from release 2024-04-12*
3. *Added documentation about the BYO UAMI feature*
4. *Aligned documentation about BYON feature with the parameter file structure change
5. *Added Hybrid VM alerts to the policy initiatives page*
6. *Update remediation page*

### Breaking Changes

1. *NONE*

## As part of this Pull Request I have

- [X] Read the Contribution Guide and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/azure-monitor-baseline-alerts/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [ ] Ensured PR tests are passing
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by bzabber** [comment]
@Brunoga-MS  Looking at your PR and the table for the Hybrid Initiative and my only complaint is that the name doesn't follow the same format as the other tables. The policy name should use underscores between the words. as shown in the image below.
This should also be fixed in the Notifications Inititaive. ;)

cc: @arjenhuitema 

image

**Comment by bzabber** [comment]
@Brunoga-MS Ignore the Notifications Initiative policy update in our documentation, I forgot that I was going to fix that! :P

**Comment by Brunoga-MS** [comment]
@bzabber we are now showing the policy display name. it does not contain underscores.

**Review by arjenhuitema — APPROVED** [review]
LGTM

**Pull request merged**
