### PR TITLE
Update Deploy-only-Service-Health-Alerts.md

### PR DESCRIPTION
**Pull request by tagolovina**
Edited Custom deployment step 5, change command and added note for Azure Cloud Shell

### CODE REVIEW

**Review by Brunoga-MS — COMMENTED** [review]
@tagolovina : is the text in the note a command sample? if so, I would suggest to not make it a note, but clearly call it example

**Comment by tagolovina** [comment]
@Brunoga-MS , changed the note.

**Review by Brunoga-MS — APPROVED** [review]
LGTM now

**Review by arjenhuitema — APPROVED** [review]
LGTM

**Pull request merged**
