### PR TITLE
Lz2alerts

### PR DESCRIPTION
**Pull request by Alboroni**
# Overview/Summary

Addition of Landing Zone Alerts coving Traffic Manager, Frontdoor, s and App Service plan base alerts t o the LZ initiative

## This PR fixes/adds/changes/removes

1. Adds 14 new alert files 
2. Updates patterns\alz\policySetDefinitions\Deploy-LandingZone-Alerts.json with new alerts 

### Breaking Changes

1. None but adding more parameters to LZ initiative
2. *Replace me*

## As part of this Pull Request I have

- [ x] Read the Contribution Guide and ensured this PR is compliant with the guide
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/azure-monitor-baseline-alerts/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [x] Ensured PR tests are passing
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.) (to be done in separate request)

### CODE REVIEW

**Review by Alboroni — COMMENTED** [review]
Look good to me

**Review by arjenhuitema — APPROVED** [review]
LGTM. 

Deployment is ok.
image

Remediation works and alerts are created:

App Service
image

Front door (classic)
image

Front door (cdn profile)
image

Traffic manager
image

**Comment by arjenhuitema** [comment]
@Alboroni everything's good, just need to resolve the merge conflict.

**Review by arjenhuitema — APPROVED** [review]
LGTM

**Pull request merged**
