### PR TITLE
Fixing VSCode error with policies.json file

### PR DESCRIPTION
**Pull request by Brunoga-MS**
# Overview/Summary

1. Aligned API version used to deploy policy to a newer one.
2. Changed policyDefinitionId" value to not include the managementGroup().Name function which was creating template validation issue in VSCode as per GH Issue [Linked template validation failed #43](https://github.com/Azure/azure-monitor-baseline-alerts/issues/43). The change has been done on the following files:

- patterns\alz\policySteDefinitions\Deploy-Connectivity-Alerts.json
- patterns\alz\policySteDefinitions\Deploy-Identity-Alerts.json
- patterns\alz\policySteDefinitions\Deploy-LandinZone-Alerts.json
- patterns\alz\policySteDefinitions\Deploy-Management-Alerts.json
- patterns\alz\policySteDefinitions\Deploy-ServiceHealth-Alerts.json

This work is related to bug [GH Issue 43: Linked template validation failed](https://dev.azure.com/CSUSolEng/Azure%20Landing%20Zones/_workitems/edit/31540)

## This PR fixes/adds/changes/removes

1. Aligned the API version used in the template part where we do deploy policies from 2019-10-01 to 2020-10-01
2. lines where the managementGroup().name function was used from **_"policyDefinitionId": "[concat('/providers/Microsoft.Management/managementGroups/',managementGroup().name,_** to **_"policyDefinitionId": "[concat('/providers/Microsoft.Management/managementGroups/contoso',_**

### Breaking Changes

1. NONE

## As part of this Pull Request I have

- [X] Read the Contribution Guide and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/azure-monitor-baseline-alerts/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [X] Ensured PR tests are passing
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by Brunoga-MS** [comment]
Adding screenshots of testing phase:

Deployment

image

image

Policies

image

Assignments

image

**Comment by Brunoga-MS** [comment]
As per conversation with @arjenhuitema , it has been decided to not fix the issue with the **_platformManagementGroup_** parameter defined but not being used, since we forecast some possible future use.

**Review by arjenhuitema — CHANGES_REQUESTED** [review]
Hi Bruno, 

I had reviewed earlier and asked why contoso is hard coded, but I understood the change now, the bicep template actually changes that hardcoded value. I´ll review in more detail later. Looking at this I assume that the issue was in the managementGroup().name and not in the API version, is that correct?

**Comment by Brunoga-MS** [comment]
Basically yes, it was just the managementGroup().name.- The API could also be one cause of validation issue on linked/nested templates, so I thought about keeping it aligned (with other resources in the same template as well)

**Review by arjenhuitema — APPROVED** [review]
LGTM

**Pull request merged**
